name: maple_closet
description: A new Flutter project.
publish_to: none
# 버전코드 여기다가 적어주면 됨
version: 1.4.1+9
environment:
  sdk: '>=3.1.0-35.0.dev <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.4
  dio: ^5.3.3
  drift: ^2.13.0
  sqlite3_flutter_libs: ^0.5.0
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  path_provider: ^2.1.1
  path: ^1.8.3
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5
  cherry_toast: ^1.11.0
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  drift_dev: ^2.13.0
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
flutter_launcher_icons:
  android: launcher_icon
  ios: true
  image_path: assets/icon.png
  min_sdk_android: 21
  web:
    generate: true
    image_path: assets/icon.png
    background_color: '#hexcode'
    theme_color: '#hexcode'
  windows:
    generate: true
    image_path: assets/icon.png
    icon_size: 48
  macos:
    generate: true
    image_path: assets/icon.png
flutter:
  uses-material-design: true
  assets:
    - assets/map/background/background_henesis.png
    - assets/map/background/background_kerningcity.png
    - assets/map/background/background_arcana.png
    - assets/map/background/background_sernium.png
    - assets/map/icon/icon_henesis.jpg
    - assets/map/icon/icon_kerningcity.jpg
    - assets/map/icon/icon_arcana.jpg
    - assets/map/icon/icon_sernium.jpg
    - assets/maple_styler_item_db.sqlite
    - assets/drummingBunny.gif